-- Generated by the database client.
CREATE TABLE chaine_hoteliere(
    nom_chaine varchar(255) NOT NULL,
    nbr_hotel integer,
    numero integer,
    rue varchar(255),
    ville varchar(255),
    province varchar(2),
    pays varchar(255),
    code_postal varchar(6),
    PRIMARY KEY(nom_chaine)
);